######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 5 16:07:58 2016
######################################################################

TEMPLATE = app
TARGET = a3
DEPENDPATH += . include src
INCLUDEPATH += . include
MOC_DIR = ./moc/
OBJECTS_DIR = ./obj/
DESTDIR = ./bin/

# Input
HEADERS += include/ClockWindow.h
SOURCES += src/ClockWindow.cc src/main.cc
